version: '3'

services:
  nginx:
    image: pterois-nginx:1.0
    ports:
      - 1337:80
    depends_on:
      - pterois
    volumes:
      - static_volume:/app/staticfiles
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=pteroisdb
      - POSTGRES_USER=pteroisdb
      - POSTGRES_DB=pteroisdb
    healthcheck:
      test: ['CMD-SHELL', 'psql -h localhost -U $${POSTGRES_USER} -c select 1 -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.0.12
    expose:
      - 6379
  pterois:
    image : pterois:1.0
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

    volumes:
      - static_volume:/app/staticfiles
      - type: bind
        source: ./local_settings_docker.py
        target: /app/djangoproject/local_settings_docker.py
        read_only: true
  rqworker:
    image: pterois:1.0
    entrypoint: poetry run python manage.py rqworker default
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - static_volume:/app/staticfiles
      - type: bind
        source: ./local_settings_docker.py
        target: /app/djangoproject/local_settings_docker.py
        read_only: true

volumes:
  postgres_data:
  static_volume: