version: '3'

services:
  nginx:
    image: niconoe/gbif-alert-nginx:1.7.6
    ports:
      - "1337:80"
    depends_on:
      - gbif-alert
    volumes:
      - static_volume:/app/staticfiles
  db:
    image: postgis/postgis:15-3.3
    platform: linux/amd64
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=gbif-alert-db
      - POSTGRES_USER=gbif-alert-db
      - POSTGRES_DB=gbif-alert-db
    healthcheck:
      test: ['CMD-SHELL', 'psql -h localhost -U $${POSTGRES_USER} -c select 1 -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.0.12
    expose:
      - 6379
  gbif-alert:
    image : niconoe/gbif-alert:1.7.6
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

    volumes:
      - static_volume:/app/staticfiles
      - type: bind
        source: ./local_settings_docker.py
        target: /app/djangoproject/local_settings_docker.py
        read_only: true
  rqworker:
    image: niconoe/gbif-alert:1.7.6
    entrypoint: poetry run python manage.py rqworker default
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - static_volume:/app/staticfiles
      - type: bind
        source: ./local_settings_docker.py
        target: /app/djangoproject/local_settings_docker.py
        read_only: true

volumes:
  postgres_data:
  static_volume: