/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/species/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Species List */
        get: operations["dashboard_api_v2_species_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/datasets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets List */
        get: operations["dashboard_api_v2_datasets_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/areas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Areas List */
        get: operations["dashboard_api_v2_areas_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/basis-of-record/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Basis Of Record List */
        get: operations["dashboard_api_v2_basis_of_record_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/data-imports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Imports List */
        get: operations["dashboard_api_v2_data_imports_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** SpeciesOut */
        SpeciesOut: {
            /** Id */
            id: number;
            /** Scientificname */
            scientificName: string;
            /** Vernacularname */
            vernacularName: string;
            /** Gbiftaxonkey */
            gbifTaxonKey: number;
            /** Tags */
            tags: string[];
        };
        /** DatasetOut */
        DatasetOut: {
            /** Id */
            id: number;
            /** Gbifkey */
            gbifKey: string;
            /** Name */
            name: string;
        };
        /** AreaOut */
        AreaOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Isuserspecific */
            isUserSpecific: boolean;
            /** Tags */
            tags: string[];
        };
        /** BasisOfRecordOut */
        BasisOfRecordOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** DataImportOut */
        DataImportOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Starttimestamp
             * Format: date-time
             */
            startTimestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dashboard_api_v2_species_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesOut"][];
                };
            };
        };
    };
    dashboard_api_v2_datasets_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"][];
                };
            };
        };
    };
    dashboard_api_v2_areas_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaOut"][];
                };
            };
        };
    };
    dashboard_api_v2_basis_of_record_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasisOfRecordOut"][];
                };
            };
        };
    };
    dashboard_api_v2_data_imports_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataImportOut"][];
                };
            };
        };
    };
}
