/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/species/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Species List */
        get: operations["dashboard_api_v2_species_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/datasets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets List */
        get: operations["dashboard_api_v2_datasets_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/areas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Areas List */
        get: operations["dashboard_api_v2_areas_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/basis-of-record/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Basis Of Record List */
        get: operations["dashboard_api_v2_basis_of_record_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/data-imports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Imports List */
        get: operations["dashboard_api_v2_data_imports_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Observations List */
        get: operations["dashboard_api_v2_observations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/histogram/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Observations Histogram */
        get: operations["dashboard_api_v2_observations_histogram"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/{stable_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Observation Detail */
        get: operations["dashboard_api_v2_observation_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/{stable_id}/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Observation Add Comment */
        post: operations["dashboard_api_v2_observation_add_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/{stable_id}/mark-unseen/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Observation Mark Unseen */
        post: operations["dashboard_api_v2_observation_mark_unseen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** SpeciesOut */
        SpeciesOut: {
            /** Id */
            id: number;
            /** Scientificname */
            scientificName: string;
            /** Vernacularname */
            vernacularName: string;
            /** Gbiftaxonkey */
            gbifTaxonKey: number;
            /** Tags */
            tags: string[];
        };
        /** DatasetOut */
        DatasetOut: {
            /** Id */
            id: number;
            /** Gbifkey */
            gbifKey: string;
            /** Name */
            name: string;
        };
        /** AreaOut */
        AreaOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Isuserspecific */
            isUserSpecific: boolean;
            /** Tags */
            tags: string[];
        };
        /** BasisOfRecordOut */
        BasisOfRecordOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** DataImportOut */
        DataImportOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Starttimestamp
             * Format: date-time
             */
            startTimestamp: string;
        };
        /** FiltersQuery */
        FiltersQuery: {
            /** Speciesids */
            speciesIds?: number[];
            /** Datasetsids */
            datasetsIds?: number[];
            /** Basisofrecordids */
            basisOfRecordIds?: number[];
            /** Startdate */
            startDate?: string | null;
            /** Enddate */
            endDate?: string | null;
            /** Areaids */
            areaIds?: number[];
            /** Status */
            status?: string | null;
            /** Initialdataimportids */
            initialDataImportIds?: number[];
            /**
             * Verifiedfilter
             * @default all
             */
            verifiedFilter: string;
            /**
             * Areafiltermode
             * @default inside
             */
            areaFilterMode: string;
            /** Approachingdistancekm */
            approachingDistanceKm?: number | null;
        };
        /** ObservationOut */
        ObservationOut: {
            /** Id */
            id: number;
            /** Stableid */
            stableId: string;
            /** Gbifid */
            gbifId: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Scientificname */
            scientificName: string;
            /** Vernacularname */
            vernacularName: string;
            /** Datasetname */
            datasetName: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Seenbycurrentuser */
            seenByCurrentUser?: boolean | null;
        };
        /** ObservationsPageOut */
        ObservationsPageOut: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["ObservationOut"][];
        };
        /** HistogramEntryOut */
        HistogramEntryOut: {
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Count */
            count: number;
        };
        /** CommentOut */
        CommentOut: {
            /** Id */
            id: number;
            /** Authorusername */
            authorUsername: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Text */
            text: string | null;
            /** Deletedbecauseauthordeleted */
            deletedBecauseAuthorDeleted: boolean;
        };
        /** ObservationDetailOut */
        ObservationDetailOut: {
            /** Id */
            id: number;
            /** Stableid */
            stableId: string;
            /** Gbifid */
            gbifId: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Scientificname */
            scientificName: string;
            /** Vernacularname */
            vernacularName: string;
            /** Datasetname */
            datasetName: string;
            /** Datasetgbifkey */
            datasetGbifKey: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Individualcount */
            individualCount: number | null;
            /** Locality */
            locality: string;
            /** Municipality */
            municipality: string;
            /** Recordedby */
            recordedBy: string;
            /** References */
            references: string;
            /** Identificationverificationstatus */
            identificationVerificationStatus: string;
            /** Verified */
            verified: boolean;
            /** Basisofrecord */
            basisOfRecord: string;
            /** Coordinateuncertaintyinmeters */
            coordinateUncertaintyInMeters: number | null;
            /** Initialdataimport */
            initialDataImport: string;
            /** Seenbycurrentuser */
            seenByCurrentUser: boolean | null;
            /** Canbemarkedunseen */
            canBeMarkedUnseen: boolean;
            /** Adminurl */
            adminUrl: string | null;
            /** Comments */
            comments: components["schemas"]["CommentOut"][];
        };
        /** CommentIn */
        CommentIn: {
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dashboard_api_v2_species_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesOut"][];
                };
            };
        };
    };
    dashboard_api_v2_datasets_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"][];
                };
            };
        };
    };
    dashboard_api_v2_areas_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaOut"][];
                };
            };
        };
    };
    dashboard_api_v2_basis_of_record_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasisOfRecordOut"][];
                };
            };
        };
    };
    dashboard_api_v2_data_imports_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataImportOut"][];
                };
            };
        };
    };
    dashboard_api_v2_observations_list: {
        parameters: {
            query?: {
                speciesIds?: number[];
                datasetsIds?: number[];
                basisOfRecordIds?: number[];
                startDate?: string | null;
                endDate?: string | null;
                areaIds?: number[];
                status?: string | null;
                initialDataImportIds?: number[];
                verifiedFilter?: string;
                areaFilterMode?: string;
                approachingDistanceKm?: number | null;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationsPageOut"];
                };
            };
        };
    };
    dashboard_api_v2_observations_histogram: {
        parameters: {
            query?: {
                speciesIds?: number[];
                datasetsIds?: number[];
                basisOfRecordIds?: number[];
                startDate?: string | null;
                endDate?: string | null;
                areaIds?: number[];
                status?: string | null;
                initialDataImportIds?: number[];
                verifiedFilter?: string;
                areaFilterMode?: string;
                approachingDistanceKm?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistogramEntryOut"][];
                };
            };
        };
    };
    dashboard_api_v2_observation_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stable_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationDetailOut"];
                };
            };
        };
    };
    dashboard_api_v2_observation_add_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stable_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentOut"];
                };
            };
        };
    };
    dashboard_api_v2_observation_mark_unseen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stable_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
