/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/species/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Species List */
        get: operations["dashboard_api_v2_species_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/datasets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets List */
        get: operations["dashboard_api_v2_datasets_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/areas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Areas List */
        get: operations["dashboard_api_v2_areas_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/basis-of-record/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Basis Of Record List */
        get: operations["dashboard_api_v2_basis_of_record_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/data-imports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Imports List */
        get: operations["dashboard_api_v2_data_imports_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List observations
         * @description Return a paginated, filtered, and sorted page of observations.
         *
         *     Pagination is controlled by `page` (1-based) and `pageSize` (capped at 100).
         *     Sorting is controlled by `orderBy` and `orderDir`. A secondary sort on `-pk`
         *     is always appended to guarantee stable pagination when the primary field has ties.
         */
        get: operations["dashboard_api_v2_observations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/histogram/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Observations Histogram */
        get: operations["dashboard_api_v2_observations_histogram"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/{stable_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Observation Detail */
        get: operations["dashboard_api_v2_observation_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/{stable_id}/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Observation Add Comment */
        post: operations["dashboard_api_v2_observation_add_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/page-fragments/{identifier}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Page Fragment
         * @description Return the rendered HTML for a page fragment in the current request language.
         *
         *     Returns {"html": ""} if the fragment does not exist, so callers never need
         *     to handle 404 - a missing fragment simply shows nothing.
         */
        get: operations["dashboard_api_v2_page_fragment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/{stable_id}/mark-unseen/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Observation Mark Unseen */
        post: operations["dashboard_api_v2_observation_mark_unseen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/alerts/suggest-name/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alert Suggest Name
         * @description Suggest the next available 'My alert #N' name for the current user.
         */
        get: operations["dashboard_api_v2_alert_suggest_name"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/alerts/notification-frequencies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alert Notification Frequencies
         * @description List available email notification frequency choices.
         */
        get: operations["dashboard_api_v2_alert_notification_frequencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/alerts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alerts List
         * @description Return all alerts belonging to the authenticated user.
         */
        get: operations["dashboard_api_v2_alerts_list"];
        put?: never;
        /**
         * Alert Create
         * @description Create a new alert for the authenticated user.
         */
        post: operations["dashboard_api_v2_alert_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/alerts/{alert_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alert Detail
         * @description Return one alert. 404 if it does not belong to the current user.
         */
        get: operations["dashboard_api_v2_alert_detail"];
        /**
         * Alert Update
         * @description Update an existing alert. 404 if it does not belong to the current user.
         */
        put: operations["dashboard_api_v2_alert_update"];
        post?: never;
        /**
         * Alert Delete
         * @description Delete an alert. 404 if it does not belong to the current user.
         */
        delete: operations["dashboard_api_v2_alert_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/alerts/{alert_id}/as-filters/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alert As Filters V2
         * @description Return the alert's filters in DashboardFilters shape for pre-loading the index page.
         */
        get: operations["dashboard_api_v2_alert_as_filters_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** SpeciesOut */
        SpeciesOut: {
            /** Id */
            id: number;
            /** Scientificname */
            scientificName: string;
            /** Vernacularname */
            vernacularName: string;
            /** Gbiftaxonkey */
            gbifTaxonKey: number;
            /** Tags */
            tags: string[];
        };
        /** DatasetOut */
        DatasetOut: {
            /** Id */
            id: number;
            /** Gbifkey */
            gbifKey: string;
            /** Name */
            name: string;
        };
        /** AreaOut */
        AreaOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Isuserspecific */
            isUserSpecific: boolean;
            /** Tags */
            tags: string[];
        };
        /** BasisOfRecordOut */
        BasisOfRecordOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** DataImportOut */
        DataImportOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Starttimestamp
             * Format: date-time
             */
            startTimestamp: string;
        };
        /** FiltersQuery */
        FiltersQuery: {
            /** Speciesids */
            speciesIds?: number[];
            /** Datasetsids */
            datasetsIds?: number[];
            /** Basisofrecordids */
            basisOfRecordIds?: number[];
            /** Startdate */
            startDate?: string | null;
            /** Enddate */
            endDate?: string | null;
            /** Areaids */
            areaIds?: number[];
            /** Status */
            status?: string | null;
            /** Initialdataimportids */
            initialDataImportIds?: number[];
            /**
             * Verifiedfilter
             * @default all
             */
            verifiedFilter: string;
            /**
             * Areafiltermode
             * @default inside
             */
            areaFilterMode: string;
            /** Approachingdistancekm */
            approachingDistanceKm?: number | null;
        };
        /** ObservationOut */
        ObservationOut: {
            /** Id */
            id: number;
            /** Stableid */
            stableId: string;
            /** Gbifid */
            gbifId: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Scientificname */
            scientificName: string;
            /** Vernacularname */
            vernacularName: string;
            /** Datasetname */
            datasetName: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Municipality */
            municipality: string;
            /** Verified */
            verified: boolean;
            /** Identificationverificationstatus */
            identificationVerificationStatus: string;
            /** Basisofrecord */
            basisOfRecord: string;
            /** Seenbycurrentuser */
            seenByCurrentUser?: boolean | null;
        };
        /** ObservationsPageOut */
        ObservationsPageOut: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["ObservationOut"][];
        };
        /** HistogramEntryOut */
        HistogramEntryOut: {
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Count */
            count: number;
        };
        /** CommentOut */
        CommentOut: {
            /** Id */
            id: number;
            /** Authorusername */
            authorUsername: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Text */
            text: string | null;
            /** Deletedbecauseauthordeleted */
            deletedBecauseAuthorDeleted: boolean;
        };
        /** ObservationDetailOut */
        ObservationDetailOut: {
            /** Id */
            id: number;
            /** Stableid */
            stableId: string;
            /** Gbifid */
            gbifId: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Scientificname */
            scientificName: string;
            /** Vernacularname */
            vernacularName: string;
            /** Datasetname */
            datasetName: string;
            /** Datasetgbifkey */
            datasetGbifKey: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Individualcount */
            individualCount: number | null;
            /** Locality */
            locality: string;
            /** Municipality */
            municipality: string;
            /** Recordedby */
            recordedBy: string;
            /** References */
            references: string;
            /** Identificationverificationstatus */
            identificationVerificationStatus: string;
            /** Verified */
            verified: boolean;
            /** Basisofrecord */
            basisOfRecord: string;
            /** Coordinateuncertaintyinmeters */
            coordinateUncertaintyInMeters: number | null;
            /** Initialdataimport */
            initialDataImport: string;
            /** Seenbycurrentuser */
            seenByCurrentUser: boolean | null;
            /** Canbemarkedunseen */
            canBeMarkedUnseen: boolean;
            /** Adminurl */
            adminUrl: string | null;
            /** Comments */
            comments: components["schemas"]["CommentOut"][];
        };
        /** CommentIn */
        CommentIn: {
            /** Text */
            text: string;
        };
        /** AlertNotificationFrequencyOut */
        AlertNotificationFrequencyOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** AlertOut */
        AlertOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Speciesids */
            speciesIds: number[];
            /** Datasetids */
            datasetIds: number[];
            /** Basisofrecordids */
            basisOfRecordIds: number[];
            /** Areaids */
            areaIds: number[];
            /** Emailnotificationsfrequency */
            emailNotificationsFrequency: string;
            /** Verifiedfilter */
            verifiedFilter: string;
            /** Areafiltermode */
            areaFilterMode: string;
            /** Approachingdistancekm */
            approachingDistanceKm: number | null;
            /** Unseencount */
            unseenCount: number;
            /** Speciesdetails */
            speciesDetails: components["schemas"]["AlertSpeciesOut"][];
            /** Specieslist */
            speciesList: string;
            /** Areadescription */
            areaDescription: string;
            /** Areanames */
            areaNames: string[];
            /** Datasetnames */
            datasetNames: string[];
            /** Datasetslist */
            datasetsList: string;
            /** Basisofrecordlist */
            basisOfRecordList: string;
            /** Verifiedfilterdisplay */
            verifiedFilterDisplay: string;
            /** Emailnotificationsfrequencydisplay */
            emailNotificationsFrequencyDisplay: string;
            /** Lastemailsenton */
            lastEmailSentOn: string | null;
        };
        /** AlertSpeciesOut */
        AlertSpeciesOut: {
            /** Scientificname */
            scientificName: string;
            /** Vernacularname */
            vernacularName: string;
        };
        /** AlertValidationErrorOut */
        AlertValidationErrorOut: {
            /** Errors */
            errors: {
                [key: string]: string[];
            };
        };
        /** AlertIn */
        AlertIn: {
            /** Name */
            name: string;
            /** Speciesids */
            speciesIds: number[];
            /** Datasetids */
            datasetIds?: number[];
            /** Basisofrecordids */
            basisOfRecordIds?: number[];
            /** Areaids */
            areaIds?: number[];
            /**
             * Emailnotificationsfrequency
             * @default W
             */
            emailNotificationsFrequency: string;
            /**
             * Verifiedfilter
             * @default all
             */
            verifiedFilter: string;
            /**
             * Areafiltermode
             * @default inside
             */
            areaFilterMode: string;
            /** Approachingdistancekm */
            approachingDistanceKm?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dashboard_api_v2_species_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesOut"][];
                };
            };
        };
    };
    dashboard_api_v2_datasets_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"][];
                };
            };
        };
    };
    dashboard_api_v2_areas_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaOut"][];
                };
            };
        };
    };
    dashboard_api_v2_basis_of_record_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasisOfRecordOut"][];
                };
            };
        };
    };
    dashboard_api_v2_data_imports_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataImportOut"][];
                };
            };
        };
    };
    dashboard_api_v2_observations_list: {
        parameters: {
            query?: {
                speciesIds?: number[];
                datasetsIds?: number[];
                basisOfRecordIds?: number[];
                startDate?: string | null;
                endDate?: string | null;
                areaIds?: number[];
                status?: string | null;
                initialDataImportIds?: number[];
                verifiedFilter?: string;
                areaFilterMode?: string;
                approachingDistanceKm?: number | null;
                page?: number;
                pageSize?: number;
                orderBy?: string;
                orderDir?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationsPageOut"];
                };
            };
        };
    };
    dashboard_api_v2_observations_histogram: {
        parameters: {
            query?: {
                speciesIds?: number[];
                datasetsIds?: number[];
                basisOfRecordIds?: number[];
                startDate?: string | null;
                endDate?: string | null;
                areaIds?: number[];
                status?: string | null;
                initialDataImportIds?: number[];
                verifiedFilter?: string;
                areaFilterMode?: string;
                approachingDistanceKm?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistogramEntryOut"][];
                };
            };
        };
    };
    dashboard_api_v2_observation_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stable_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationDetailOut"];
                };
            };
        };
    };
    dashboard_api_v2_observation_add_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stable_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentOut"];
                };
            };
        };
    };
    dashboard_api_v2_page_fragment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    dashboard_api_v2_observation_mark_unseen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stable_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    dashboard_api_v2_alert_suggest_name: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    dashboard_api_v2_alert_notification_frequencies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertNotificationFrequencyOut"][];
                };
            };
        };
    };
    dashboard_api_v2_alerts_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
        };
    };
    dashboard_api_v2_alert_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertValidationErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_alert_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
        };
    };
    dashboard_api_v2_alert_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertValidationErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_alert_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dashboard_api_v2_alert_as_filters_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
