"""
Django settings for djangoproject project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

from django.utils.translation import gettext_lazy as _

BASE_DIR = Path(__file__).resolve().parent.parent

from dotenv import load_dotenv

# Load .env from the project root if it exists. No-op if env vars are
# already set (compose, systemd EnvironmentFile, shell exports, etc.).
# This is the ONLY .env this project loads: local_settings.py must NOT load
# its own .env (a second, later load would race the env-driven config below -
# e.g. CACHES is built before it and would miss a late CACHE_URL).
load_dotenv(BASE_DIR / ".env")

# ---------------------------------------------------------------------------
# Environment-driven configuration.
#
# All operationally-significant settings come from environment variables with
# sensible defaults. `local_settings.py` (imported at the end of this module)
# may override any of these - that is the per-deployment escape hatch for
# callable values like PREDICATE_BUILDER.
#
# Reads use `.get()` rather than `[]` so the module can load even when an env
# var is missing. Final validation happens at the end of this module, after
# the escape hatch has had a chance to set values from a Python file.
# ---------------------------------------------------------------------------

SECRET_KEY = os.environ.get("SECRET_KEY", "")
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

# GeoDjango finds GDAL/GEOS automatically on Linux/Docker. On macOS (Homebrew)
# the libraries usually need explicit paths - set them via env (or in
# local_settings.py) so local dev runs under the default settings module too.
if _gdal := os.environ.get("GDAL_LIBRARY_PATH"):
    GDAL_LIBRARY_PATH = _gdal
if _geos := os.environ.get("GEOS_LIBRARY_PATH"):
    GEOS_LIBRARY_PATH = _geos
# `ALLOWED_HOSTS` carries two kinds of entries:
#   1. Hosts the operator declared via `DJANGO_ALLOWED_HOSTS` (what the
#      validation at the end of this module cares about).
#   2. Loopback addresses, always appended, so in-container healthchecks
#      (the compose healthcheck hits `http://localhost:8000/healthz`) and
#      `manage.py runserver` debugging work without operators having to
#      remember them. Added attack surface is minimal: external clients
#      sending `Host: localhost` against a reverse-proxied deploy still
#      get filtered by the proxy's own host validation.
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]
for _loopback in ("localhost", "127.0.0.1"):
    if _loopback not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_loopback)

# CSRF_TRUSTED_ORIGINS must include the scheme (e.g. "https://example.org").
# Required when Django is behind a reverse proxy on a custom domain: since
# Django 4.0, the CSRF middleware verifies the browser-sent Origin header
# against this allowlist on every unsafe (POST/PUT/DELETE) request.
# Comma-separated via env var.
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# Trust the X-Forwarded-Proto header from the reverse proxy so that
# request.is_secure() returns True for HTTPS requests terminated at the
# proxy. Used for secure-cookie behavior and absolute URL building.
# Safe here because the supported proxies (Traefik, nginx) overwrite this
# header rather than forwarding a client-supplied value - if you put a
# different proxy in front, verify it does the same before trusting this.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SITE_BASE_URL = os.environ.get("SITE_BASE_URL", "")

import dj_database_url

# DATABASES is set only if DATABASE_URL is present. Leaving it unset lets
# local_settings.py define DATABASES the old way (explicit dict) without
# env vars - useful for the manual deploy that pre-dates this refactor.
if database_url := os.environ.get("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.parse(database_url, conn_max_age=600),
    }

from urllib.parse import urlparse

# RQ_QUEUES is always defined (django_rq raises ImproperlyConfigured at app
# load time if it is missing). When RQ_REDIS_URL is unset we fall back to
# `redis://localhost:6379/0` - a sensible default for a single-host manual
# deploy. Operators with different topology (Docker, ECS, etc.) set
# RQ_REDIS_URL to point at their broker. The escape-hatch import at the end
# of this module lets local_settings.py replace RQ_QUEUES wholesale.
_rq_url = urlparse(os.environ.get("RQ_REDIS_URL", "redis://localhost:6379/0"))
RQ_QUEUES = {
    "default": {
        "HOST": _rq_url.hostname or "localhost",
        "PORT": _rq_url.port or 6379,
        "DB": int(_rq_url.path.lstrip("/")) if _rq_url.path.lstrip("/") else 0,
        "PASSWORD": _rq_url.password or None,
        "DEFAULT_TIMEOUT": 360,
    },
}

# Cache. Used by maintenance_mode (CacheBackend) to share state across
# gunicorn workers, rqworker and the ofelia-triggered import_observations
# command. Defaults to localhost:6379/0 - the same default RQ uses - so
# dev and prod take the exact same code path. CACHE_URL is an optional
# override; set it to point the cache at a different Redis DB from the
# RQ queue (e.g. CACHE_URL=redis://valkey:6379/1 vs RQ_REDIS_URL=.../0)
# in deployments that want the two isolated.
_cache_url = (
    os.environ.get("CACHE_URL", "")
    or os.environ.get("RQ_REDIS_URL", "")
    or "redis://localhost:6379/0"
)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": _cache_url,
    }
}

# Email backend defaults to SMTP. Override via local_settings.py if you need
# the console backend for dev or LocMemEmailBackend for tests.
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "25"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "False").lower() == "true"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "")
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", DEFAULT_FROM_EMAIL)
EMAIL_SUBJECT_PREFIX = os.environ.get("EMAIL_SUBJECT_PREFIX", "[gbif-alert] ")

# ADMINS is parsed from a single env var of the form "Name1 <a@b>, Name2 <c@d>"
_admins_raw = os.environ.get("ADMINS", "")
ADMINS: list[tuple[str, str]] = []
if _admins_raw:
    import re
    for entry in _admins_raw.split(","):
        entry = entry.strip()
        if not entry:
            continue
        match = re.match(r"^(.*?)\s*<(.+?)>$", entry)
        if match:
            ADMINS.append((match.group(1).strip(), match.group(2).strip()))
        else:
            # Bare email: name = email
            ADMINS.append((entry, entry))

# ---------------------------------------------------------------------------
# GBIF_ALERT settings (per-deployment branding, behaviour, and GBIF download
# config). Each key is constructed from env vars; local_settings.py may
# replace the entire dict or override individual keys after this module's
# import.
# ---------------------------------------------------------------------------


def _default_predicate_builder(species_list):
    """Default GBIF download predicate builder.

    Builds a predicate from `GBIF_DOWNLOAD_COUNTRY` and `GBIF_DOWNLOAD_YEAR_MIN`.
    Operators with more complex predicate needs override this in
    `local_settings.py` by setting `GBIF_ALERT["GBIF_DOWNLOAD_CONFIG"]["PREDICATE_BUILDER"]`.
    """
    predicates: list[dict] = [
        {
            "type": "in",
            "key": "TAXON_KEY",
            "values": [str(s.gbif_taxon_key) for s in species_list],
        },
        {"type": "equals", "key": "OCCURRENCE_STATUS", "value": "present"},
    ]
    if country := os.environ.get("GBIF_DOWNLOAD_COUNTRY"):
        predicates.append({"type": "equals", "key": "COUNTRY", "value": country})
    if year_min := os.environ.get("GBIF_DOWNLOAD_YEAR_MIN"):
        predicates.append(
            {"type": "greaterThanOrEquals", "key": "YEAR", "value": int(year_min)}
        )
    return {"predicate": {"type": "and", "predicates": predicates}}


GBIF_ALERT: dict = {
    "SITE_NAME": os.environ.get("SITE_NAME", ""),
    "PRIMEVUE_PRIMARY_PALETTE": os.environ.get("PRIMEVUE_PRIMARY_PALETTE", "indigo"),
    "ENABLED_LANGUAGES": tuple(
        s.strip()
        for s in os.environ.get("ENABLED_LANGUAGES", "en,fr,nl").split(",")
        if s.strip()
    ),
    "GBIF_DOWNLOAD_CONFIG": {
        "USERNAME": os.environ.get("GBIF_DOWNLOAD_USERNAME", ""),
        "PASSWORD": os.environ.get("GBIF_DOWNLOAD_PASSWORD", ""),
        "PREDICATE_BUILDER": _default_predicate_builder,
    },
    "MAIN_MAP_CONFIG": {
        "initialZoom": int(os.environ.get("MAP_INITIAL_ZOOM", "2")),
        "initialLat": float(os.environ.get("MAP_INITIAL_LAT", "0")),
        "initialLon": float(os.environ.get("MAP_INITIAL_LON", "0")),
    },
}


# Application definition

INSTALLED_APPS = [
    # Django
    "modeltranslation",  # Must be placed before the admin app: https://github.com/deschler/django-modeltranslation/issues/408
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "django.contrib.humanize",
    # Third-party
    "maintenance_mode",
    "import_export",
    "corsheaders",
    "markdownx",
    "django_rq",
    "taggit",
    "gisserver",
    # Beware, there's also "modeltranslation", but it had to be placed before the admin app
    "django_vite",
    # Local/custom
    "dashboard",
    "page_fragments",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "maintenance_mode.middleware.MaintenanceModeMiddleware",
]

ROOT_URLCONF = "djangoproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "dashboard.context_processors.latest_data_import_processor",
                "dashboard.context_processors.gbif_alert_settings",
                "dashboard.context_processors.gbif_alert_various",
            ],
        },
    },
]

WSGI_APPLICATION = "djangoproject.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

# Beware: when adding a new language, you also need to run `python manage.py makemigrations` (it is referenced from the user profile model)
LANGUAGES = [
    ("en", _("English")),
    ("fr", _("French")),
    ("nl", _("Dutch")),
]

TIME_ZONE = os.environ.get("TIME_ZONE", "Europe/Brussels")

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"


STATICFILES_DIRS: list[str] = [os.path.join(BASE_DIR, "static_global")]
STATIC_ROOT = os.path.join(BASE_DIR, "static")

DJANGO_VITE = {
    "default": {
        "dev_mode": False,  # override to True in local_settings.py when running the Vite dev server
        "dev_server_port": 5274,
        "manifest_path": BASE_DIR / "static_global" / "vite" / ".vite" / "manifest.json",
        # Vite outputs to static_global/vite/, so assets are served at /static/vite/...
        # This prefix is used both in dev (to construct the dev server URL matching
        # vite.config.ts base: "/static/vite/") and in production (prepended before
        # staticfiles_storage.url() so the URL resolves to /static/vite/assets/...).
        "static_url_prefix": "vite",
    }
}

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "djangoproject.storage.ViteAwareStaticStorage",
    },
}

# Public API v2 rate limits (django-ninja throttling). Anonymous requests are
# limited per IP, authenticated (session or token) per user. Override per
# deployment via the environment. Map tiles under /internal-api/ are separate.
API_V2_THROTTLE_ANON = os.environ.get("API_V2_THROTTLE_ANON", "60/min")
API_V2_THROTTLE_AUTH = os.environ.get("API_V2_THROTTLE_AUTH", "600/min")


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "dashboard.User"

LOGIN_URL = "signin"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_METHODS = [
    "GET"
]  # Probably needed, but just to be on the safe side. See https://github.com/riparias/gbif-alert/issues/100

PAGE_FRAGMENTS_FALLBACK_LANGUAGE = "en"

RQ_SHOW_ADMIN_LINK = True

# We have to explicitly set the various maintenance mode default settings because of https://github.com/fabiocaccamo/django-maintenance-mode/issues/59
MAINTENANCE_MODE = None
# CacheBackend uses the Django cache configured above. It catches cache
# errors internally and falls back to STATE_BACKEND_FALLBACK_VALUE, so a
# Valkey outage degrades to "not in maintenance mode" rather than crashing
# every request - the failure mode that caused this setting to exist.
MAINTENANCE_MODE_STATE_BACKEND = "maintenance_mode.backends.CacheBackend"
MAINTENANCE_MODE_STATE_BACKEND_FALLBACK_VALUE = False
MAINTENANCE_MODE_IGNORE_ADMIN_SITE = False
MAINTENANCE_MODE_IGNORE_ANONYMOUS_USER = False
MAINTENANCE_MODE_IGNORE_AUTHENTICATED_USER = False
MAINTENANCE_MODE_IGNORE_STAFF = False
MAINTENANCE_MODE_IGNORE_SUPERUSER = False
MAINTENANCE_MODE_IGNORE_IP_ADDRESSES = ()
MAINTENANCE_MODE_GET_CLIENT_IP_ADDRESS = None
MAINTENANCE_MODE_IGNORE_URLS = ()
MAINTENANCE_MODE_IGNORE_TESTS = False
MAINTENANCE_MODE_REDIRECT_URL = None
MAINTENANCE_MODE_TEMPLATE = "dashboard/503.html"
MAINTENANCE_MODE_GET_CONTEXT = None
MAINTENANCE_MODE_STATUS_CODE = 503
MAINTENANCE_MODE_RETRY_AFTER = 3600
MAINTENANCE_MODE_LOGOUT_AUTHENTICATED_USER = False
MAINTENANCE_MODE_RESPONSE_TYPE = "html"

# Logging: unfortunately for us, I am not able to override the default logging config as suggested in Django's documentation (changes are ignored)
# This is similar to https://stackoverflow.com/questions/62334688/django-logger-not-logging-but-all-other-loggers-work
# I therefore copy-pasted the default config from Django's source code and modified it to my needs.
# Currently applied changes:
# - Added a filter to ignore 503 errors when in maintenance mode
# - "include_html": True for the emails to admins in case of errors
LOGGING_CONFIG = None
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
        "require_not_maintenance_mode_503": {
            "()": "maintenance_mode.logging.RequireNotMaintenanceMode503",
        },
    },
    "formatters": {
        "django.server": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[{server_time}] {message}",
            "style": "{",
        }
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
        },
        "django.server": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "django.server",
        },
        "mail_admins": {
            "level": "ERROR",
            "filters": ["require_debug_false", "require_not_maintenance_mode_503"],
            "class": "django.utils.log.AdminEmailHandler",
            "include_html": True,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "mail_admins"],
            "level": "INFO",
        },
        "django.server": {
            "handlers": ["django.server"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
import logging.config

logging.config.dictConfig(LOGGING)

MARKDOWNX_MARKDOWN_EXTENSIONS = ["markdown.extensions.toc"]

TAGGIT_CASE_INSENSITIVE = True

SELENIUM_HEADLESS_MODE = True

# Hexagon size (in meters) according to the zoom level. Adjust ZOOM_TO_HEX_SIZE_MULTIPLIER to simultaneously configure
# all zoom levels

ZOOM_TO_HEX_SIZE_MULTIPLIER = 2
ZOOM_TO_HEX_SIZE_BASELINE = {
    0: 640000,
    1: 320000,
    2: 160000,
    3: 80000,
    4: 40000,
    5: 20000,
    6: 10000,
    7: 5000,
    8: 2500,
    9: 1250,
    10: 675,
    11: 335,
    12: 160,
    13: 80,
    14: 80,
    # At higher zoom levels, the map shows the individual points
}
ZOOM_TO_HEX_SIZE = {
    key: value * ZOOM_TO_HEX_SIZE_MULTIPLIER
    for key, value in ZOOM_TO_HEX_SIZE_BASELINE.items()
}

# The zoom level at which the minimum and maximum values are queried
# That's the only zoom level where this calculation is done
# By consequence, we generate a materialized view for this zoom level, so
# the endpoint has good performances. We initially generated those views at each zoom
# level, but it's lengthy (during import), eats disk space and is unnecessary.
# The test suite also make sure the endpoint works at different zoom levels, so it
# will need to generate more materialized views (so the endpoint works), but it's only
# when running tests and with a tiny amount of data.
ZOOM_LEVEL_FOR_MIN_MAX_QUERY = 8


# ---------------------------------------------------------------------------
# Optional per-deployment Python overrides.
#
# `local_settings.py` may define or override any setting. This is the escape
# hatch used by both the manual deploy (host file) and the Docker bind-mount.
# It is imported AFTER all env-driven settings, so its values take precedence.
# It is an OVERRIDE LAYER, not an entry point: the settings module is always
# `djangoproject.settings` (wsgi/asgi/manage/Docker all agree), and this import
# pulls in local_settings.py on top. local_settings.py should therefore contain
# only overrides - no `from .settings import *`, no `load_dotenv`.
#
# The guard below is belt-and-suspenders: if someone still points
# DJANGO_SETTINGS_MODULE directly at a local_settings module (the old style),
# skip the re-import to avoid a circular import.
# ---------------------------------------------------------------------------

_settings_module = os.environ.get("DJANGO_SETTINGS_MODULE", "")
if not _settings_module.startswith("djangoproject.local_settings"):
    try:
        # mypy: local_settings.py is operator-supplied and may legitimately
        # not exist (e.g. in CI or a fresh Docker image); the ImportError
        # branch handles that at runtime.
        from djangoproject.local_settings import *  # type: ignore[import] # noqa: F401, F403
    except ImportError:
        pass

# ---------------------------------------------------------------------------
# Validation.
#
# Catches missing required settings whether they come from env vars or from
# local_settings.py. Run only when settings.py is the entry point - under the
# legacy `DJANGO_SETTINGS_MODULE=djangoproject.local_settings*` chain,
# validation happens naturally when local_settings finishes loading.
# ---------------------------------------------------------------------------

if not _settings_module.startswith("djangoproject.local_settings"):
    from django.core.exceptions import ImproperlyConfigured

    _missing = []
    if not SECRET_KEY:
        _missing.append("SECRET_KEY")
    if not SITE_BASE_URL:
        _missing.append("SITE_BASE_URL")
    # ALLOWED_HOSTS is intentionally NOT validated here: the loopback
    # entries auto-added near the top of this module guarantee it is
    # never empty, and a misconfigured host raises DisallowedHost on
    # the first request with a clear error message anyway.
    if "default" not in globals().get("DATABASES", {}):
        _missing.append("DATABASE_URL or DATABASES")
    if _missing:
        raise ImproperlyConfigured(
            "Required settings not configured: "
            + ", ".join(_missing)
            + ". Set them via environment variables (or define them in "
            "djangoproject/local_settings.py)."
        )
