# Generated by Django 4.0.3 on 2022-03-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_squashed_0004_auto_20220324_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataimport',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='observation',
            name='references',
            field=models.TextField(blank=True),
        ),
    ]
