# Generated by Django 3.2.11 on 2022-01-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='gbif_predicate',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
