# Generated by Django 3.2.11 on 2022-01-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dataimport_gbif_predicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='skipped_observations_counter',
            field=models.IntegerField(default=0),
        ),
    ]
