# Generated by Django 3.2.12 on 2022-03-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_observation_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_email_sent_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
