# Generated by Django 3.2.12 on 2022-03-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alert_last_email_sent_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name_plural': 'species'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='areas',
            field=models.ManyToManyField(blank=True, help_text='Optional (no selection = notify me for all areas). To select multiple items, press and hold the Ctrl or Command key and click the items.', to='dashboard.Area'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='datasets',
            field=models.ManyToManyField(blank=True, help_text='Optional (no selection = notify me for all datasets). To select multiple items, press and hold the Ctrl or Command key and click the items.', to='dashboard.Dataset'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='species',
            field=models.ManyToManyField(blank=True, help_text='Optional (no selection = notify me for all species). To select multiple items, press and hold the Ctrl or Command key and click the items.', to='dashboard.Species'),
        ),
    ]
