# Generated by Django 4.0.6 on 2022-07-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_species_vernacular_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
