# Generated by Django 4.0.6 on 2022-07-05 07:18

from django.db import migrations


def set_alert_names(apps, schema_editor):
    Alert = apps.get_model("dashboard", "Alert")
    for alert in Alert.objects.all():
        alert.name = f"Alert #{alert.pk}"
        alert.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alert_name"),
    ]

    operations = [
        migrations.RunPython(set_alert_names),
    ]
