# Generated by Django 4.1.7 on 2023-02-20 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_alert_name_alter_alert_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="observationcomment",
            name="emptied_because_author_deleted_account",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="observationcomment",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
