# Generated by Django 4.1.7 on 2023-02-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0007_observationcomment_emptied_because_author_deleted_account_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("email",)},
        ),
    ]
