# Generated by Django 4.1.7 on 2023-03-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_alter_user_options_alter_user_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_visit_news_page",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
