# Generated by Django 3.2.10 on 2021-12-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20211214_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='coordinate_uncertainty_in_meters',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
