# Generated by Django 4.1.7 on 2023-03-23 13:28

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("dashboard", "0009_user_last_visit_news_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="species",
            name="group",
        ),
        migrations.AddField(
            model_name="species",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
