# Generated by Django 3.2.10 on 2021-12-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_occurrence_coordinate_uncertainty_in_meters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='basis_of_record',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='locality',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='municipality',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='recorded_by',
            field=models.TextField(blank=True),
        ),
    ]
