# Generated by Django 4.2 on 2023-04-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0012_user_language_alter_alert_areas_alter_alert_datasets_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="vernacular_name_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="vernacular_name_fr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="vernacular_name_nl",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
