# Generated by Django 3.2.10 on 2021-12-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='email_notifications_frequency',
            field=models.CharField(choices=[('N', 'No emails'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default='W', max_length=3),
        ),
    ]
