# Generated by Django 4.2 on 2023-06-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0013_species_vernacular_name_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="areas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional (no selection = notify me for all data in the system). To select multiple items, press and hold the Ctrl or Command key and click the items.",
                to="dashboard.area",
                verbose_name="areas",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="species",
            field=models.ManyToManyField(
                help_text="To select multiple items, press and hold the Ctrl or Command key and click the items.",
                to="dashboard.species",
                verbose_name="species",
            ),
        ),
    ]
