# Generated by Django 4.2.2 on 2023-06-06 09:14

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("dashboard", "0015_explicit_alert_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
