# Generated by Django 3.2.10 on 2021-12-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_rename_imported_occurrences_counter_dataimport_imported_observations_counter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Occurrence',
            new_name='Observation',
        ),
    ]
