# Generated by Django 3.2.10 on 2021-12-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_rename_occurrence_observation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OccurrenceComment',
            new_name='ObservationComment',
        ),
    ]
