# Generated by Django 3.2.10 on 2021-12-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_rename_occurrencecomment_observationcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observationcomment',
            old_name='occurrence',
            new_name='observation',
        ),
    ]
