# Generated by Django 4.2.13 on 2024-06-05 12:36

from django.db import migrations


def migrate_obs_views_new_mechanism(apps, schema_editor):
    Observation = apps.get_model("dashboard", "Observation")
    User = apps.get_model("dashboard", "User")

    for obs in Observation.objects.all().prefetch_related():
        for user in User.objects.all():
            if not obs.observationview_set.filter(user=user).exists():
                obs.observationunseen_set.create(user=user)


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0018_observationunseen"),
    ]

    operations = [migrations.RunPython(migrate_obs_views_new_mechanism)]
