# Generated by Django 4.2.13 on 2024-10-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0018_observationunseen"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_delay_days",
            field=models.IntegerField(default=365),
        ),
    ]
