# Generated by Django 3.2.10 on 2021-12-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_occurrence_observationcomment_observation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OccurrenceView',
            new_name='ObservationView',
        ),
    ]
