# Generated by Django 3.2.10 on 2021-12-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_rename_occurrenceview_observationview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observationview',
            old_name='occurrence',
            new_name='observation',
        ),
        migrations.AlterUniqueTogether(
            name='observationview',
            unique_together={('observation', 'user')},
        ),
    ]
