# Generated by Django 3.2.10 on 2021-12-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20211222_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='category',
        ),
    ]
