# Generated by Django 3.2.10 on 2022-01-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_species_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='areas',
            field=models.ManyToManyField(blank=True, help_text='Is restricted to the following areas', to='dashboard.Area'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='datasets',
            field=models.ManyToManyField(blank=True, help_text='Is restricted to the following datasets', to='dashboard.Dataset'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='species',
            field=models.ManyToManyField(blank=True, help_text='Is restricted to the following species', to='dashboard.Species'),
        ),
    ]
