# Generated by Django 4.2.28 on 2026-02-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0024_finalize_basis_of_record_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="identification_verification_status",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
