# Generated by Django 4.2.28 on 2026-03-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0027_alert_verified_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="approaching_distance_km",
            field=models.FloatField(
                blank=True,
                help_text="Required when area_filter_mode is 'approaching' or 'both'. Distance in km.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="area_filter_mode",
            field=models.CharField(
                choices=[
                    ("inside", "Inside the area"),
                    ("approaching", "Close to the area (not inside)"),
                    ("both", "Inside or close to the area"),
                ],
                default="inside",
                max_length=20,
            ),
        ),
    ]
