# Generated by Django 5.2.15 on 2026-06-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0031_apitoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="image_attribution",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="species",
            name="image_license",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="species",
            name="image_source_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Manual"),
                    ("wikipedia", "Wikipedia/Wikimedia"),
                    ("gbif", "GBIF occurrence media"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="image_source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="species",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
