# Generated by Django 5.2.15 on 2026-06-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0032_species_image_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="image_attribution",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="species",
            name="image_source_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="species",
            name="image_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
