# Generated by Django 5.2.15 on 2026-07-07 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0033_species_image_field_lengths"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_filter_mode",
                    models.CharField(
                        choices=[
                            ("inside", "Inside the area"),
                            ("approaching", "Close to the area (not inside)"),
                            ("both", "Inside or close to the area"),
                        ],
                        default="inside",
                        max_length=20,
                    ),
                ),
                (
                    "approaching_distance_km",
                    models.FloatField(
                        blank=True,
                        help_text="Required when area_filter_mode is 'approaching' or 'both'. Distance in km (max 50).",
                        null=True,
                    ),
                ),
                (
                    "verified_filter",
                    models.CharField(
                        choices=[
                            ("all", "All observations"),
                            ("verified", "Verified only"),
                            ("unverified", "Unverified only"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_fr", models.CharField(max_length=255, null=True)),
                ("name_nl", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_nl", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "areas",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional (no selection = notify me for all data in the system). To select multiple items, press and hold the Ctrl or Command key and click the items.",
                        to="dashboard.area",
                        verbose_name="areas",
                    ),
                ),
                (
                    "basis_of_record_filters",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional (no selection = notify me for all basis of records). To select multiple items, press and hold the Ctrl or Command key and click the items.",
                        to="dashboard.basisofrecord",
                        verbose_name="basis of record",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_alert_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "datasets",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional (no selection = notify me for all datasets). To select multiple items, press and hold the Ctrl or Command key and click the items.",
                        to="dashboard.dataset",
                        verbose_name="datasets",
                    ),
                ),
                (
                    "species",
                    models.ManyToManyField(
                        help_text="To select multiple items, press and hold the Ctrl or Command key and click the items.",
                        to="dashboard.species",
                        verbose_name="species",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="alert",
            name="created_from_template",
            field=models.ForeignKey(
                blank=True,
                help_text="The template this alert was copied from, if any (traceability only).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_alerts",
                to="dashboard.alerttemplate",
            ),
        ),
    ]
