# Generated by Django 5.2.15 on 2026-07-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0034_alerttemplate_alert_created_from_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="gbif_col_taxon_key",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
