# Generated by Django 5.2.15 on 2026-07-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0035_add_gbif_col_taxon_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="gbif_taxon_key",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
