# Generated by Django 5.2.15 on 2026-08-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0038_drop_redundant_unseen_user_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="is_default_home_filter",
            field=models.BooleanField(
                default=False,
                help_text="Pre-select this area as the home page's default filter. Public areas only. Visitors can remove it like any other filter.",
            ),
        ),
    ]
