# Generated by Django 5.2.15 on 2026-08-21 14:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0039_area_is_default_home_filter"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=3857)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="dashboard.area",
                    ),
                ),
            ],
        ),
    ]
