# Generated by Django 5.2.15 on 2026-09-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0041_backfill_area_parts"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerttemplate",
            name="description_nb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alerttemplate",
            name="name_nb",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="vernacular_name_nb",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "French"),
                    ("nl", "Dutch"),
                    ("nb", "Norwegian Bokmal"),
                ],
                default="en-us",
                max_length=10,
            ),
        ),
    ]
