# Generated by Django 5.2.15 on 2026-09-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0042_add_nb_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapBaseLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "layer_type",
                    models.CharField(
                        choices=[("xyz", "XYZ tiles"), ("wms", "WMS")],
                        default="xyz",
                        max_length=3,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="XYZ: the tile template, with the {z}, {x} and {y} placeholders (use {-y} for TMS row ordering). Drop any {r} retina placeholder, OpenLayers does not support it. WMS: the service endpoint, without parameters. The service must serve EPSG:3857.",
                        max_length=500,
                    ),
                ),
                (
                    "wms_layers",
                    models.CharField(
                        blank=True,
                        help_text="WMS only: comma-separated layer names (the LAYERS parameter).",
                        max_length=255,
                    ),
                ),
                (
                    "attribution",
                    models.CharField(
                        blank=True,
                        help_text="Credit shown in the map corner. Most tile providers require this; check the provider's terms.",
                        max_length=500,
                    ),
                ),
                ("max_zoom", models.PositiveSmallIntegerField(default=19)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide the layer without deleting it.",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Position in the picker. Maps open with the first enabled layer.",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
    ]
