# Generated by Django 5.2.17 on 2026-09-29 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0045_area_owner_cascade"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObservationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.TextField()),
                ("references", models.TextField(blank=True)),
                ("license", models.TextField(blank=True)),
                ("attribution", models.TextField(blank=True)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="dashboard.observation",
                    ),
                ),
            ],
        ),
    ]
