# Generated by Django 5.2.17 on 2026-10-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0046_observationimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataimport",
            name="skipped_observations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
