# Generated by Django 5.2.17 on 2026-10-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0047_dataimport_skipped_observations"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="has_images",
            field=models.BooleanField(default=False),
        ),
        # Flag the observations already imported with images, so the gallery
        # does not stay empty until the next import. Before the index, so it is
        # built once.
        migrations.RunSQL(
            "UPDATE dashboard_observation SET has_images = true "
            "WHERE id IN (SELECT observation_id FROM dashboard_observationimage)",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                condition=models.Q(("has_images", True)),
                fields=["date", "id"],
                name="dashboard_o_img_date_id_idx",
            ),
        ),
    ]
