/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/species/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Species List */
        get: operations["dashboard_api_v2_species_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/species/per-polygon/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Species Per Polygon
         * @description Species occurring within the given polygon, each with its observation count.
         *
         *     The polygon is a GeoJSON FeatureCollection in EPSG:4326, sent in the request
         *     body. (The legacy endpoint took WKT in the query string - audit N1.)
         */
        post: operations["dashboard_api_v2_species_per_polygon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/datasets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets List */
        get: operations["dashboard_api_v2_datasets_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/areas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Areas List */
        get: operations["dashboard_api_v2_areas_list"];
        put?: never;
        /**
         * Area Create
         * @description Create a new user-specific area from an uploaded GeoPackage file.
         *
         *     Returns 422 with a human-readable detail message if the file fails
         *     validation (wrong geometry type, multiple layers, missing SRS, etc.).
         */
        post: operations["dashboard_api_v2_area_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/areas/{area_id}/geojson/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Area Geojson
         * @description Return GeoJSON (FeatureCollection, EPSG:4326) for a single area.
         *
         *     Available to any user who can access the area (public or owned).
         *     Returns 403 if the area exists but the user cannot access it.
         *     Returns 404 if the area does not exist.
         */
        get: operations["dashboard_api_v2_area_geojson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/areas/from-drawing/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Area Create From Drawing
         * @description Create a new user-specific area from a GeoJSON FeatureCollection.
         *
         *     Accepts a GeoJSON FeatureCollection (EPSG:4326) with Polygon or MultiPolygon
         *     features drawn by the user. All features are merged into a single MultiPolygon.
         *
         *     Returns 422 with a detail message if the geometry is invalid.
         */
        post: operations["dashboard_api_v2_area_create_from_drawing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/areas/{area_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Area Delete
         * @description Delete a user-owned area.
         *
         *     Returns 404 if the area does not exist or belongs to another user.
         *     Returns 409 with a detail message if any alerts reference this area.
         */
        delete: operations["dashboard_api_v2_area_delete"];
        options?: never;
        head?: never;
        /**
         * Area Patch
         * @description Update the name and/or geometry of a user-owned area.
         *
         *     Both fields are optional. Passing geojson=None leaves the geometry unchanged.
         *     Returns 404 if the area does not exist or belongs to another user.
         */
        patch: operations["dashboard_api_v2_area_patch"];
        trace?: never;
    };
    "/api/v2/basis-of-record/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Basis Of Record List */
        get: operations["dashboard_api_v2_basis_of_record_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/data-imports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Imports List */
        get: operations["dashboard_api_v2_data_imports_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List observations
         * @description Return a paginated, filtered, and sorted page of observations.
         *
         *     Pagination is controlled by `page` (1-based) and `pageSize` (must be 1-100).
         *     Sorting is controlled by `orderBy` and `orderDir`. A secondary sort on `-pk`
         *     is always appended to guarantee stable pagination when the primary field has ties.
         *     Invalid `orderBy`, `orderDir`, `page`, or `pageSize` values return 400.
         */
        get: operations["dashboard_api_v2_observations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/histogram/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Observations Histogram */
        get: operations["dashboard_api_v2_observations_histogram"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/counter/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Observations Counter
         * @description Return only the count of observations matching the filters - a lightweight
         *     alternative to the full list when the consumer just needs the number.
         *
         *     Defined before observation_detail so the literal `/observations/counter/`
         *     path is matched ahead of `/observations/{stable_id}/`.
         */
        get: operations["dashboard_api_v2_observations_counter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/mark-as-viewed/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Observations Mark All As Seen
         * @description Bulk-mark all observations matching the given filters as seen by the
         *     requesting user. Runs asynchronously via django-rq.
         *
         *     Filters are read from the JSON request body (a mutating POST carries its
         *     payload in the body, not the query string - audit N4).
         */
        post: operations["dashboard_api_v2_observations_mark_all_as_seen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/{stable_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Observation Detail */
        get: operations["dashboard_api_v2_observation_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/{stable_id}/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Observation Add Comment */
        post: operations["dashboard_api_v2_observation_add_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/{stable_id}/mark-as-viewed/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Observation Mark As Seen
         * @description Mark a single observation as seen by the requesting user.
         *
         *     Replaces the implicit side effect that the detail GET used to perform, so
         *     that GET stays safe/idempotent (audit M11).
         */
        post: operations["dashboard_api_v2_observation_mark_as_seen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/observations/{stable_id}/mark-as-not-viewed/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Observation Mark As Unseen */
        post: operations["dashboard_api_v2_observation_mark_as_unseen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/alerts/notification-frequencies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alert Notification Frequencies
         * @description List available email notification frequency choices.
         */
        get: operations["dashboard_api_v2_alert_notification_frequencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/alerts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alerts List
         * @description Return all alerts belonging to the authenticated user.
         */
        get: operations["dashboard_api_v2_alerts_list"];
        put?: never;
        /**
         * Alert Create
         * @description Create a new alert for the authenticated user.
         */
        post: operations["dashboard_api_v2_alert_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/alerts/{alert_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alert Detail
         * @description Return one alert. 404 if it does not belong to the current user.
         */
        get: operations["dashboard_api_v2_alert_detail"];
        /**
         * Alert Update
         * @description Update an existing alert. 404 if it does not belong to the current user.
         */
        put: operations["dashboard_api_v2_alert_update"];
        post?: never;
        /**
         * Alert Delete
         * @description Delete an alert. 404 if it does not belong to the current user.
         */
        delete: operations["dashboard_api_v2_alert_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/signin/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth Signin
         * @description Authenticate and create a session. Returns 401 on bad credentials.
         */
        post: operations["dashboard_api_v2_auth_signin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/signup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth Signup
         * @description Create an account and log in. Returns 422 with field errors on failure.
         */
        post: operations["dashboard_api_v2_auth_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/password-change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth Password Change
         * @description Change password. Returns 204 on success, 422 with field errors on failure.
         */
        post: operations["dashboard_api_v2_auth_password_change"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profile Get
         * @description Return the current user's editable profile fields.
         */
        get: operations["dashboard_api_v2_profile_get"];
        /**
         * Profile Put
         * @description Save profile changes. Returns 422 with field errors on duplicate email.
         */
        put: operations["dashboard_api_v2_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/account/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Account Delete
         * @description Delete the current user account and log out.
         */
        delete: operations["dashboard_api_v2_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/api-tokens/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Tokens List
         * @description List the current user's API tokens (never the secret value).
         */
        get: operations["dashboard_api_v2_api_tokens_list"];
        put?: never;
        /**
         * Api Token Create
         * @description Create a token and return its raw value once (never retrievable again).
         */
        post: operations["dashboard_api_v2_api_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/api-tokens/{token_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Api Token Delete
         * @description Revoke one of the current user's tokens.
         */
        delete: operations["dashboard_api_v2_api_token_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** SpeciesOut */
        SpeciesOut: {
            /** Id */
            id: number;
            /** Scientificname */
            scientificName: string;
            /** Vernacularnameen */
            vernacularNameEn: string;
            /** Vernacularnamenl */
            vernacularNameNl: string;
            /** Vernacularnamefr */
            vernacularNameFr: string;
            /**
             * Gbiftaxonkey
             * @description GBIF taxon key. Numeric in GBIF's data model, so returned as an integer. Distinct from `gbifId` (an occurrence identifier) which GBIF models as a string - the int/str split is intrinsic to GBIF, not an inconsistency in this API.
             */
            gbifTaxonKey: number;
            /** Tags */
            tags: string[];
        };
        /** SpeciesPerPolygonOut */
        SpeciesPerPolygonOut: {
            /** Id */
            id: number;
            /** Scientificname */
            scientificName: string;
            /** Vernacularnameen */
            vernacularNameEn: string;
            /** Vernacularnamenl */
            vernacularNameNl: string;
            /** Vernacularnamefr */
            vernacularNameFr: string;
            /**
             * Gbiftaxonkey
             * @description GBIF taxon key. Numeric in GBIF's data model, so returned as an integer. Distinct from `gbifId` (an occurrence identifier) which GBIF models as a string - the int/str split is intrinsic to GBIF, not an inconsistency in this API.
             */
            gbifTaxonKey: number;
            /** Tags */
            tags: string[];
            /** Observationcountinpolygon */
            observationCountInPolygon: number;
        };
        /**
         * DetailErrorOut
         * @description Single-message error envelope.
         *
         *     Used for all 4xx responses that do not carry per-field validation details.
         *     Equivalent in shape to django-ninja's default error body, made explicit so
         *     every endpoint declares it in its `response={...}` map and it appears in
         *     the OpenAPI schema.
         */
        DetailErrorOut: {
            /** Detail */
            detail: string;
        };
        /** SpeciesPerPolygonIn */
        SpeciesPerPolygonIn: {
            /** Geojson */
            geojson: {
                [key: string]: unknown;
            };
        };
        /** DatasetOut */
        DatasetOut: {
            /** Id */
            id: number;
            /** Gbifdatasetkey */
            gbifDatasetKey: string;
            /** Name */
            name: string;
        };
        /** AreaOut */
        AreaOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Isuserspecific */
            isUserSpecific: boolean;
            /** Tags */
            tags: string[];
        };
        /**
         * GeoJSONFeatureCollectionOut
         * @description A GeoJSON FeatureCollection (EPSG:4326) from Django's geojson serializer.
         *
         *     Coordinates are WGS84 (EPSG:4326). Django's geojson serializer dropped the
         *     non-standard `crs` member in 5.0 (per RFC 7946), so the wire format is just
         *     `type` + `features`.
         */
        GeoJSONFeatureCollectionOut: {
            /** Type */
            type: string;
            /** Features */
            features: components["schemas"]["GeoJSONFeatureOut"][];
        };
        /**
         * GeoJSONFeatureOut
         * @description A single GeoJSON Feature as produced by Django's geojson serializer.
         *
         *     `geometry` and `properties` are passed through untyped - the schema
         *     documents the Feature envelope without constraining the geometry internals.
         */
        GeoJSONFeatureOut: {
            /** Type */
            type: string;
            /** Id */
            id: number;
            /** Properties */
            properties: {
                [key: string]: unknown;
            };
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            } | null;
        };
        /** AreaFromDrawingIn */
        AreaFromDrawingIn: {
            /** Name */
            name: string;
            /** Geojson */
            geojson: {
                [key: string]: unknown;
            };
        };
        /** AreaPatchIn */
        AreaPatchIn: {
            /** Name */
            name?: string | null;
            /** Geojson */
            geojson?: {
                [key: string]: unknown;
            } | null;
        };
        /** BasisOfRecordOut */
        BasisOfRecordOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** DataImportOut */
        DataImportOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /** Endedat */
            endedAt: string | null;
            /** Importedcount */
            importedCount: number;
            /** Newobservationscount */
            newObservationsCount: number;
            /** Skippedcount */
            skippedCount: number;
            /** Gbifdownloadid */
            gbifDownloadId: string;
        };
        /** FiltersQuery */
        FiltersQuery: {
            /** Speciesids */
            speciesIds?: number[];
            /** Datasetids */
            datasetIds?: number[];
            /** Basisofrecordids */
            basisOfRecordIds?: number[];
            /** Startdate */
            startDate?: string | null;
            /** Enddate */
            endDate?: string | null;
            /** Areaids */
            areaIds?: number[];
            /** Status */
            status?: ("all" | "viewed" | "notViewed") | null;
            /** Initialdataimportids */
            initialDataImportIds?: number[];
            /**
             * Verifiedfilter
             * @default all
             * @enum {string}
             */
            verifiedFilter: "all" | "verified" | "unverified";
            /**
             * Areafiltermode
             * @default inside
             * @enum {string}
             */
            areaFilterMode: "inside" | "approaching" | "both";
            /** Approachingdistancekm */
            approachingDistanceKm?: number | null;
        };
        /** ObservationOut */
        ObservationOut: {
            /** Id */
            id: number;
            /** Stableid */
            stableId: string;
            /**
             * Gbifid
             * @description GBIF occurrence identifier. A string in GBIF's data model (unlike the numeric `gbifTaxonKey` on species), and returned as a string for fidelity to GBIF. The int/str split is intrinsic, not a bug.
             */
            gbifId: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Scientificname */
            scientificName: string;
            /** Vernacularnameen */
            vernacularNameEn: string;
            /** Vernacularnamenl */
            vernacularNameNl: string;
            /** Vernacularnamefr */
            vernacularNameFr: string;
            /** Datasetname */
            datasetName: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Municipality */
            municipality: string;
            /** Verified */
            verified: boolean;
            /** Identificationverificationstatus */
            identificationVerificationStatus: string;
            /** Basisofrecordid */
            basisOfRecordId: number;
            /** Basisofrecordname */
            basisOfRecordName: string;
            /** Viewedbycurrentuser */
            viewedByCurrentUser?: boolean | null;
        };
        /** ObservationsPageOut */
        ObservationsPageOut: {
            /** Count */
            count: number;
            /** Speciescount */
            speciesCount: number;
            /** Datasetscount */
            datasetsCount: number;
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Totalpages */
            totalPages: number;
            /** Hasnextpage */
            hasNextPage: boolean;
            /** Haspreviouspage */
            hasPreviousPage: boolean;
            /** Items */
            items: components["schemas"]["ObservationOut"][];
        };
        /** HistogramEntryOut */
        HistogramEntryOut: {
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Count */
            count: number;
        };
        /**
         * CountOut
         * @description The number of observations matching a filter set.
         */
        CountOut: {
            /** Count */
            count: number;
        };
        /**
         * QueuedOut
         * @description Acknowledgement that a bulk operation was queued for async processing.
         *
         *     `count` is the number of rows the operation will affect (e.g. matching
         *     observations currently unseen by the user, for bulk mark-as-seen).
         */
        QueuedOut: {
            /** Queued */
            queued: boolean;
            /** Count */
            count: number;
        };
        /** CommentOut */
        CommentOut: {
            /** Id */
            id: number;
            /** Authorusername */
            authorUsername: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Text */
            text: string | null;
            /** Deletedbecauseauthordeleted */
            deletedBecauseAuthorDeleted: boolean;
        };
        /**
         * InitialDataImportOut
         * @description The data import that first brought an observation into the system.
         */
        InitialDataImportOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
        };
        /** ObservationDetailOut */
        ObservationDetailOut: {
            /** Id */
            id: number;
            /** Stableid */
            stableId: string;
            /**
             * Gbifid
             * @description GBIF occurrence identifier. A string in GBIF's data model (unlike the numeric `gbifTaxonKey` on species), and returned as a string for fidelity to GBIF. The int/str split is intrinsic, not a bug.
             */
            gbifId: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Scientificname */
            scientificName: string;
            /** Vernacularnameen */
            vernacularNameEn: string;
            /** Vernacularnamenl */
            vernacularNameNl: string;
            /** Vernacularnamefr */
            vernacularNameFr: string;
            /** Datasetname */
            datasetName: string;
            /** Gbifdatasetkey */
            gbifDatasetKey: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Individualcount */
            individualCount: number | null;
            /** Locality */
            locality: string;
            /** Municipality */
            municipality: string;
            /** Recordedby */
            recordedBy: string;
            /** References */
            references: string;
            /** Identificationverificationstatus */
            identificationVerificationStatus: string;
            /** Verified */
            verified: boolean;
            /** Basisofrecordid */
            basisOfRecordId: number;
            /** Basisofrecordname */
            basisOfRecordName: string;
            /** Coordinateuncertaintyinmeters */
            coordinateUncertaintyInMeters: number | null;
            initialDataImport: components["schemas"]["InitialDataImportOut"];
            /** Viewedbycurrentuser */
            viewedByCurrentUser: boolean | null;
            /**
             * Canbemarkednotviewed
             * @description Per-user capability flag: true when this observation matches one of the caller's alerts and can therefore be marked not viewed. False for anonymous callers and observations outside the caller's alerts.
             */
            canBeMarkedNotViewed: boolean;
            /** Comments */
            comments: components["schemas"]["CommentOut"][];
        };
        /** CommentIn */
        CommentIn: {
            /** Text */
            text: string;
        };
        /**
         * OkOut
         * @description Simple boolean acknowledgement response.
         */
        OkOut: {
            /** Ok */
            ok: boolean;
        };
        /** AlertNotificationFrequencyOut */
        AlertNotificationFrequencyOut: {
            /**
             * Id
             * @enum {string}
             */
            id: "N" | "D" | "W" | "M";
            /** Label */
            label: string;
        };
        /** AlertOut */
        AlertOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Speciesids */
            speciesIds: number[];
            /** Datasetids */
            datasetIds: number[];
            /** Basisofrecordids */
            basisOfRecordIds: number[];
            /** Areaids */
            areaIds: number[];
            /**
             * Emailnotificationsfrequency
             * @enum {string}
             */
            emailNotificationsFrequency: "N" | "D" | "W" | "M";
            /**
             * Verifiedfilter
             * @enum {string}
             */
            verifiedFilter: "all" | "verified" | "unverified";
            /**
             * Areafiltermode
             * @enum {string}
             */
            areaFilterMode: "inside" | "approaching" | "both";
            /** Approachingdistancekm */
            approachingDistanceKm: number | null;
            /** Notviewedcount */
            notViewedCount: number;
            /** Speciesdetails */
            speciesDetails: components["schemas"]["AlertSpeciesOut"][];
            /** Lastemailsentat */
            lastEmailSentAt: string | null;
        };
        /** AlertSpeciesOut */
        AlertSpeciesOut: {
            /** Scientificname */
            scientificName: string;
            /** Vernacularnameen */
            vernacularNameEn: string;
            /** Vernacularnamenl */
            vernacularNameNl: string;
            /** Vernacularnamefr */
            vernacularNameFr: string;
        };
        /**
         * ValidationErrorOut
         * @description Field-validation error envelope.
         *
         *     Used for 422 responses that carry per-field error messages. The top-level
         *     `detail` lets clients display a generic message when they don't iterate
         *     per-field; `errors` is a map of field name to a list of validation
         *     messages for that field.
         */
        ValidationErrorOut: {
            /** Detail */
            detail: string;
            /** Errors */
            errors: {
                [key: string]: string[];
            };
        };
        /** AlertIn */
        AlertIn: {
            /** Name */
            name: string;
            /** Speciesids */
            speciesIds: number[];
            /** Datasetids */
            datasetIds?: number[];
            /** Basisofrecordids */
            basisOfRecordIds?: number[];
            /** Areaids */
            areaIds?: number[];
            /**
             * Emailnotificationsfrequency
             * @default W
             * @enum {string}
             */
            emailNotificationsFrequency: "N" | "D" | "W" | "M";
            /**
             * Verifiedfilter
             * @default all
             * @enum {string}
             */
            verifiedFilter: "all" | "verified" | "unverified";
            /**
             * Areafiltermode
             * @default inside
             * @enum {string}
             */
            areaFilterMode: "inside" | "approaching" | "both";
            /** Approachingdistancekm */
            approachingDistanceKm?: number | null;
        };
        /** SignInOut */
        SignInOut: {
            /** Username */
            username: string;
        };
        /** SignInIn */
        SignInIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** SignUpIn */
        SignUpIn: {
            /** Username */
            username: string;
            /**
             * Firstname
             * @default
             */
            firstName: string;
            /**
             * Lastname
             * @default
             */
            lastName: string;
            /** Email */
            email: string;
            /**
             * Language
             * @description A language code enabled on this site (see settings.LANGUAGES, e.g. en/fr/nl).
             */
            language: string;
            /** Password1 */
            password1: string;
            /** Password2 */
            password2: string;
        };
        /** PasswordChangeIn */
        PasswordChangeIn: {
            /** Oldpassword */
            oldPassword: string;
            /** Newpassword1 */
            newPassword1: string;
            /** Newpassword2 */
            newPassword2: string;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Username */
            username: string;
            /** Firstname */
            firstName: string;
            /** Lastname */
            lastName: string;
            /** Email */
            email: string;
            /**
             * Language
             * @description A language code enabled on this site (see settings.LANGUAGES, e.g. en/fr/nl).
             */
            language: string;
            /** Delayvalue */
            delayValue: number;
            /**
             * Delayunit
             * @enum {string}
             */
            delayUnit: "days" | "weeks" | "months" | "years";
        };
        /** ProfileIn */
        ProfileIn: {
            /** Firstname */
            firstName: string;
            /** Lastname */
            lastName: string;
            /** Email */
            email: string;
            /**
             * Language
             * @description A language code enabled on this site (see settings.LANGUAGES, e.g. en/fr/nl).
             */
            language: string;
            /** Delayvalue */
            delayValue: number;
            /**
             * Delayunit
             * @description One of: days, weeks, months, years.
             */
            delayUnit: string;
        };
        /**
         * ApiTokenOut
         * @description A personal access token, without its secret value.
         */
        ApiTokenOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Prefix */
            prefix: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Lastusedat */
            lastUsedAt: string | null;
        };
        /**
         * ApiTokenCreatedOut
         * @description Returned once on creation - carries the raw token, shown only this time.
         */
        ApiTokenCreatedOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Prefix */
            prefix: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Lastusedat */
            lastUsedAt: string | null;
            /** Token */
            token: string;
        };
        /** ApiTokenCreateIn */
        ApiTokenCreateIn: {
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dashboard_api_v2_species_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesOut"][];
                };
            };
        };
    };
    dashboard_api_v2_species_per_polygon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeciesPerPolygonIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesPerPolygonOut"][];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_datasets_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"][];
                };
            };
        };
    };
    dashboard_api_v2_areas_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaOut"][];
                };
            };
        };
    };
    dashboard_api_v2_area_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Name */
                    name: string;
                    /**
                     * Data File
                     * Format: binary
                     */
                    data_file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_area_geojson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                area_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoJSONFeatureCollectionOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_area_create_from_drawing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AreaFromDrawingIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_area_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                area_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_area_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                area_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AreaPatchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_basis_of_record_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasisOfRecordOut"][];
                };
            };
        };
    };
    dashboard_api_v2_data_imports_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataImportOut"][];
                };
            };
        };
    };
    dashboard_api_v2_observations_list: {
        parameters: {
            query?: {
                speciesIds?: number[];
                datasetIds?: number[];
                basisOfRecordIds?: number[];
                startDate?: string | null;
                endDate?: string | null;
                areaIds?: number[];
                status?: ("all" | "viewed" | "notViewed") | null;
                initialDataImportIds?: number[];
                verifiedFilter?: "all" | "verified" | "unverified";
                areaFilterMode?: "inside" | "approaching" | "both";
                approachingDistanceKm?: number | null;
                page?: number;
                pageSize?: number;
                orderBy?: string;
                orderDir?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationsPageOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_observations_histogram: {
        parameters: {
            query?: {
                speciesIds?: number[];
                datasetIds?: number[];
                basisOfRecordIds?: number[];
                startDate?: string | null;
                endDate?: string | null;
                areaIds?: number[];
                status?: ("all" | "viewed" | "notViewed") | null;
                initialDataImportIds?: number[];
                verifiedFilter?: "all" | "verified" | "unverified";
                areaFilterMode?: "inside" | "approaching" | "both";
                approachingDistanceKm?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistogramEntryOut"][];
                };
            };
        };
    };
    dashboard_api_v2_observations_counter: {
        parameters: {
            query?: {
                speciesIds?: number[];
                datasetIds?: number[];
                basisOfRecordIds?: number[];
                startDate?: string | null;
                endDate?: string | null;
                areaIds?: number[];
                status?: ("all" | "viewed" | "notViewed") | null;
                initialDataImportIds?: number[];
                verifiedFilter?: "all" | "verified" | "unverified";
                areaFilterMode?: "inside" | "approaching" | "both";
                approachingDistanceKm?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountOut"];
                };
            };
        };
    };
    dashboard_api_v2_observations_mark_all_as_seen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FiltersQuery"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuedOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_observation_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stable_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationDetailOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_observation_add_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stable_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_observation_mark_as_seen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stable_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_observation_mark_as_unseen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stable_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_alert_notification_frequencies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertNotificationFrequencyOut"][];
                };
            };
        };
    };
    dashboard_api_v2_alerts_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_alert_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_alert_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_alert_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_alert_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_auth_signin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_auth_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_auth_password_change: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeIn"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_account_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_api_tokens_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenOut"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_api_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiTokenCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenCreatedOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
    dashboard_api_v2_api_token_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailErrorOut"];
                };
            };
        };
    };
}
