# Generated by Django 3.2.12 on 2022-03-15 09:11

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.SlugField(unique=True)),
                ('content_nl', markdownx.models.MarkdownxField(blank=True)),
                ('content_en', markdownx.models.MarkdownxField(blank=True)),
                ('content_fr', markdownx.models.MarkdownxField(blank=True)),
            ],
        ),
    ]
