# Generated by Django 3.2.12 on 2022-03-15 09:11
from typing import List, Tuple

import markdownx.models  # type: ignore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="PageFragment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.SlugField(unique=True)),
                ("content_nl", markdownx.models.MarkdownxField(blank=True)),
                ("content_en", markdownx.models.MarkdownxField(blank=True)),
                ("content_fr", markdownx.models.MarkdownxField(blank=True)),
            ],
        ),
    ]
