# Generated by Django 4.1.7 on 2023-03-03 11:13

from django.db import migrations

from page_fragments.models import NEWS_PAGE_IDENTIFIER


def create_news_page_content(apps, schema_editor):
    PageFragment = apps.get_model("page_fragments", "PageFragment")
    PageFragment.objects.create(
        identifier=NEWS_PAGE_IDENTIFIER,
        content_en="",
        content_nl="",
        content_fr="",
    )


def delete_news_page_content(apps, schema_editor):
    PageFragment = apps.get_model("page_fragments", "PageFragment")
    PageFragment.objects.filter(identifier=NEWS_PAGE_IDENTIFIER).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("page_fragments", "0002_pagefragment_updated_at"),
    ]

    operations = [
        migrations.RunPython(create_news_page_content, delete_news_page_content),
    ]
